In [1]:
import numpy as np

# Practice Problem 1

In [3]:
rng=np.random.default_rng(seed=33)
some_data=rng.integers(100,450,size=(100,4))
print(some_data)


[[407 255 233 298]
 [390 417 204 188]
 [285 306 188 225]
 [424 364 399 290]
 [232 170 335 280]
 [245 184 277 117]
 [119 139 400 219]
 [142 105 430 370]
 [154 381 301 107]
 [143 284 345 251]
 [152 240 399 125]
 [324 429 318 203]
 [181 426 331 241]
 [136 173 259 187]
 [189 186 167 381]
 [270 390 332 382]
 [332 193 198 203]
 [174 288 433 349]
 [378 347 225 394]
 [194 367 114 280]
 [332 342 135 367]
 [113 167 124 442]
 [276 288 262 322]
 [174 334 247 347]
 [294 130 258 126]
 [354 204 449 146]
 [292 361 267 265]
 [355 163 368 241]
 [114 168 260 361]
 [348 240 288 398]
 [422 348 304 262]
 [280 301 423 449]
 [410 352 108 248]
 [367 238 330 398]
 [266 320 314 343]
 [195 156 192 255]
 [427 105 354 287]
 [348 107 117 327]
 [171 150 233 126]
 [321 157 189 246]
 [313 271 325 187]
 [315 318 176 312]
 [200 175 311 233]
 [293 426 422 273]
 [173 385 211 339]
 [140 328 262 409]
 [161 115 270 292]
 [234 413 376 292]
 [230 105 142 428]
 [352 359 326 232]
 [375 163 384 107]
 [142 425 358 392]
 [327 144 17

In [5]:
mean_val=np.mean(some_data[:,0])
std_val=np.std(some_data[:,0])
print(mean_val)
print(std_val)

278.01
93.92970722833111


In [9]:
lower_bound=mean_val-(2*std_val)
upper_bound=mean_val+(2*std_val)
mask=((some_data[:,0]>lower_bound)&(some_data[:,0]<upper_bound))
#or
#mask=np.abs(some_data[:,0]-mean_val)<(2*std_val)
some_data=some_data[mask]
print(some_data)

[[119 139 400 219]
 [142 105 430 370]
 [154 381 301 107]
 [143 284 345 251]
 [152 240 399 125]
 [181 426 331 241]
 [136 173 259 187]
 [174 288 433 349]
 [113 167 124 442]
 [174 334 247 347]
 [114 168 260 361]
 [171 150 233 126]
 [173 385 211 339]
 [140 328 262 409]
 [161 115 270 292]
 [142 425 358 392]
 [149 419 127 253]
 [173 405 254 258]
 [180 284 386 218]
 [148 213 121 416]
 [176 213 362 165]
 [182 167 114 385]
 [184 224 141 310]
 [140 352 276 181]
 [139 207 177 359]]


# Practice Problem 2

In [37]:
rng=np.random.default_rng(seed=42)
ages=rng.integers(0,101, size=(10,1))
incomes=rng.integers(20000,80000,size=(10,1))

X=np.hstack((ages, incomes))
print(ages)

print(X)


[[ 9]
 [78]
 [66]
 [44]
 [43]
 [86]
 [ 8]
 [70]
 [20]
 [ 9]]
[[    9 51588]
 [   78 78537]
 [   66 64145]
 [   44 65668]
 [   43 63048]
 [   86 67163]
 [    8 50793]
 [   70 27686]
 [   20 70384]
 [    9 47023]]


In [19]:
min_vals=X.min(axis=0)
max_vals=X.max(axis=0)

print(min_vals)
print(max_vals)

[    8 27686]
[   86 78537]


In [20]:
numerator=X-min_vals
denominator=max_vals-min_vals
scaled_data=numerator/denominator
print(scaled_data)



[[0.01282051 0.47003992]
 [0.8974359  1.        ]
 [0.74358974 0.71697705]
 [0.46153846 0.7469273 ]
 [0.44871795 0.69540422]
 [1.         0.77632692]
 [0.         0.45440601]
 [0.79487179 0.        ]
 [0.15384615 0.83966884]
 [0.01282051 0.38026784]]


# Practice Problem 3

In [27]:
rng=np.random.default_rng(seed=42)
A=rng.standard_normal((10,10))

print(A)

[[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
   0.1278404  -0.31624259 -0.01680116 -0.85304393]
 [ 0.87939797  0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246
   0.36875078 -0.9588826   0.8784503  -0.04992591]
 [-0.18486236 -0.68092954  1.22254134 -0.15452948 -0.42832782 -0.35213355
   0.53230919  0.36544406  0.41273261  0.430821  ]
 [ 2.1416476  -0.40641502 -0.51224273 -0.81377273  0.61597942  1.12897229
  -0.11394746 -0.84015648 -0.82448122  0.65059279]
 [ 0.74325417  0.54315427 -0.66550971  0.23216132  0.11668581  0.2186886
   0.87142878  0.22359555  0.67891356  0.06757907]
 [ 0.2891194   0.63128823 -1.45715582 -0.31967122 -0.47037265 -0.63887785
  -0.27514225  1.49494131 -0.86583112  0.96827835]
 [-1.68286977 -0.33488503  0.16275307  0.58622233  0.71122658  0.79334724
  -0.34872507 -0.46235179  0.85797588 -0.19130432]
 [-1.27568632 -1.13328721 -0.91945229  0.49716074  0.14242574  0.69048535
  -0.42725265  0.15853969  0.62559039 -0.30934654]
 

In [30]:
processed_A=np.where(A<0, 0, A)
print(processed_A)

[[0.30471708 0.         0.7504512  0.94056472 0.         0.
  0.1278404  0.         0.         0.        ]
 [0.87939797 0.77779194 0.0660307  1.12724121 0.46750934 0.
  0.36875078 0.         0.8784503  0.        ]
 [0.         0.         1.22254134 0.         0.         0.
  0.53230919 0.36544406 0.41273261 0.430821  ]
 [2.1416476  0.         0.         0.         0.61597942 1.12897229
  0.         0.         0.         0.65059279]
 [0.74325417 0.54315427 0.         0.23216132 0.11668581 0.2186886
  0.87142878 0.22359555 0.67891356 0.06757907]
 [0.2891194  0.63128823 0.         0.         0.         0.
  0.         1.49494131 0.         0.96827835]
 [0.         0.         0.16275307 0.58622233 0.71122658 0.79334724
  0.         0.         0.85797588 0.        ]
 [0.         0.         0.         0.49716074 0.14242574 0.69048535
  0.         0.15853969 0.62559039 0.        ]
 [0.45677524 0.         0.         0.         0.         0.48697248
  0.         0.01249412 0.48074666 0.44653118

# Practice Problem 4

In [31]:
rng=np.random.default_rng(seed=42)
grades=rng.integers(0,101,(10,5))
print(grades)

[[ 9 78 66 44 43]
 [86  8 70 20  9]
 [53 98 74 76 72]
 [79 51 12 84 45]
 [50 37 18 93 78]
 [65 40 83 55 44]
 [45 22  9 56 89]
 [ 6 86 83 27 63]
 [16 76 70 35  6]
 [98 45 90 68 78]]


In [38]:
mean_scores=grades.mean(axis=1)
max_scores=grades.max(axis=1)
print(mean_scores.reshape(-1,1))
print(max_scores)


[[48. ]
 [38.6]
 [74.6]
 [54.2]
 [55.2]
 [57.4]
 [44.2]
 [53. ]
 [40.6]
 [75.8]]
[78 86 98 84 93 83 89 86 76 98]


In [41]:
grades_stats=np.hstack((grades, mean_scores.reshape(-1,1), max_scores.reshape(-1,1)))
print(grades_stats)



[[ 9.  78.  66.  44.  43.  48.  78. ]
 [86.   8.  70.  20.   9.  38.6 86. ]
 [53.  98.  74.  76.  72.  74.6 98. ]
 [79.  51.  12.  84.  45.  54.2 84. ]
 [50.  37.  18.  93.  78.  55.2 93. ]
 [65.  40.  83.  55.  44.  57.4 83. ]
 [45.  22.   9.  56.  89.  44.2 89. ]
 [ 6.  86.  83.  27.  63.  53.  86. ]
 [16.  76.  70.  35.   6.  40.6 76. ]
 [98.  45.  90.  68.  78.  75.8 98. ]]


# Practice Problem 5

In [61]:
rng=np.random.default_rng(seed=42)
data=rng.integers(-1000,1000,size=(10,10))
print(data)



[[-822  547  309 -123 -134  717 -829  394 -598 -812]
 [  52  951  471  522  434  572   26 -744  679 -100]
 [   0 -259 -635  853  563  287 -196  645   90 -114]
 [-100 -546 -816  109  775 -873  716  655 -447  263]
 [-670  516  401 -291 -865  941 -109  786  355  556]
 [ 519 -611 -273  -67   -5 -913   93 -692  486  366]
 [ 845  489 -267  935 -179 -349  811 -260 -848  -61]
 [ 591 -622  -75 -741  372  -49 -340 -547  128  339]
 [ 880 -126 -679  665  259  400 -806 -376  535  664]
 [-130  609  683 -226  796 -424 -521  364  273 -721]]


In [62]:
num_rows=data.shape[0]
split_value=num_rows*0.7
print(split_value)


7.0


In [63]:
rng.shuffle(data)
training_data=data[:7,:]
test_data=data[7:,:]

print('Training data is:')
print(training_data)
print('Test data:')
print(test_data)

Training data is:
[[-822  547  309 -123 -134  717 -829  394 -598 -812]
 [   0 -259 -635  853  563  287 -196  645   90 -114]
 [-670  516  401 -291 -865  941 -109  786  355  556]
 [ 845  489 -267  935 -179 -349  811 -260 -848  -61]
 [-130  609  683 -226  796 -424 -521  364  273 -721]
 [  52  951  471  522  434  572   26 -744  679 -100]
 [-100 -546 -816  109  775 -873  716  655 -447  263]]
Test data:
[[ 880 -126 -679  665  259  400 -806 -376  535  664]
 [ 591 -622  -75 -741  372  -49 -340 -547  128  339]
 [ 519 -611 -273  -67   -5 -913   93 -692  486  366]]
